2025-02-14 13:25:10,149 - INFO - ===== PHASE 3 (ASAN) EXECUTION ENGINE STARTED =====
2025-02-14 13:25:10,149 - INFO - ===== BEGIN EXECUTION PHASE 3 (ASAN) =====
2025-02-14 13:25:10,782 - INFO - Found 118739 test files in /home/dhia/browser-fuzzer/Dissertation/tests/testing_seeds/combined.
2025-02-14 13:25:10,783 - INFO - ====== WebDriver manager ======
2025-02-14 13:25:10,914 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-14 13:25:11,000 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-14 13:25:11,084 - INFO - Driver [/home/dhia/.wdm/drivers/chromedriver/linux64/132.0.6834.159/chromedriver-linux64/chromedriver] found in cache
2025-02-14 13:25:22,721 - ERROR - [chrome] ERROR: Message: session not created: This version of ChromeDriver only supports Chrome version 132
Current browser version is 134.0.6988.0 with binary path /home/dhia/chrome-asan/chrome-asan/chrome
Stacktrace:
#0 0x56ebf8c1253a <unknown>
#1 0x56ebf870df00 <unknown>
#2 0x56ebf874c342 <unknown>
#3 0x56ebf874b235 <unknown>
#4 0x56ebf8745361 <unknown>
#5 0x56ebf87414b6 <unknown>
#6 0x56ebf878e7b6 <unknown>
#7 0x56ebf878de06 <unknown>
#8 0x56ebf8782343 <unknown>
#9 0x56ebf874f78a <unknown>
#10 0x56ebf87509de <unknown>
#11 0x56ebf8bdc2cb <unknown>
#12 0x56ebf8be0242 <unknown>
#13 0x56ebf8bc97ac <unknown>
#14 0x56ebf8be0df7 <unknown>
#15 0x56ebf8badb2f <unknown>
#16 0x56ebf8c011a8 <unknown>
#17 0x56ebf8c01370 <unknown>
#18 0x56ebf8c113b6 <unknown>
#19 0x7e719de94ac3 <unknown>

2025-02-14 13:25:22,723 - ERROR - Traceback (most recent call last):
  File "/home/dhia/browser-fuzzer/Dissertation/execution-engine/./executio_engine.py", line 150, in run_test
    driver = create_webdriver(browser_name)
  File "/home/dhia/browser-fuzzer/Dissertation/execution-engine/./executio_engine.py", line 102, in create_webdriver
    driver = webdriver.Chrome(
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 132
Current browser version is 134.0.6988.0 with binary path /home/dhia/chrome-asan/chrome-asan/chrome
Stacktrace:
#0 0x56ebf8c1253a <unknown>
#1 0x56ebf870df00 <unknown>
#2 0x56ebf874c342 <unknown>
#3 0x56ebf874b235 <unknown>
#4 0x56ebf8745361 <unknown>
#5 0x56ebf87414b6 <unknown>
#6 0x56ebf878e7b6 <unknown>
#7 0x56ebf878de06 <unknown>
#8 0x56ebf8782343 <unknown>
#9 0x56ebf874f78a <unknown>
#10 0x56ebf87509de <unknown>
#11 0x56ebf8bdc2cb <unknown>
#12 0x56ebf8be0242 <unknown>
#13 0x56ebf8bc97ac <unknown>
#14 0x56ebf8be0df7 <unknown>
#15 0x56ebf8badb2f <unknown>
#16 0x56ebf8c011a8 <unknown>
#17 0x56ebf8c01370 <unknown>
#18 0x56ebf8c113b6 <unknown>
#19 0x7e719de94ac3 <unknown>


2025-02-14 13:25:22,733 - INFO - ====== WebDriver manager ======
2025-02-14 13:25:23,402 - INFO - Get LATEST geckodriver version for 134.0 firefox
2025-02-14 13:25:23,402 - INFO - GH_TOKEN will be used to perform requests
2025-02-14 13:25:24,016 - INFO - Get LATEST geckodriver version for 134.0 firefox
2025-02-14 13:25:24,016 - INFO - GH_TOKEN will be used to perform requests
2025-02-14 13:25:24,621 - INFO - Driver [/home/dhia/.wdm/drivers/geckodriver/linux64/v0.35.0/geckodriver] found in cache
2025-02-14 13:25:42,294 - INFO - [firefox] Loading: file:///home/dhia/browser-fuzzer/Dissertation/tests/testing_seeds/combined/id:017548,time:0,execs:0,orig:percentage-heights-008.html
2025-02-14 13:25:56,987 - INFO - ====== WebDriver manager ======
2025-02-14 13:25:57,149 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-14 13:25:57,345 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-14 13:25:57,439 - INFO - Driver [/home/dhia/.wdm/drivers/chromedriver/linux64/132.0.6834.159/chromedriver-linux64/chromedriver] found in cache
2025-02-14 13:26:01,086 - ERROR - [chrome] ERROR: Message: session not created: This version of ChromeDriver only supports Chrome version 132
Current browser version is 134.0.6988.0 with binary path /home/dhia/chrome-asan/chrome-asan/chrome
Stacktrace:
#0 0x5944ef17b53a <unknown>
#1 0x5944eec76f00 <unknown>
#2 0x5944eecb5342 <unknown>
#3 0x5944eecb4235 <unknown>
#4 0x5944eecae361 <unknown>
#5 0x5944eecaa4b6 <unknown>
#6 0x5944eecf77b6 <unknown>
#7 0x5944eecf6e06 <unknown>
#8 0x5944eeceb343 <unknown>
#9 0x5944eecb878a <unknown>
#10 0x5944eecb99de <unknown>
#11 0x5944ef1452cb <unknown>
#12 0x5944ef149242 <unknown>
#13 0x5944ef1327ac <unknown>
#14 0x5944ef149df7 <unknown>
#15 0x5944ef116b2f <unknown>
#16 0x5944ef16a1a8 <unknown>
#17 0x5944ef16a370 <unknown>
#18 0x5944ef17a3b6 <unknown>
#19 0x787a90894ac3 <unknown>

2025-02-14 13:26:01,088 - ERROR - Traceback (most recent call last):
  File "/home/dhia/browser-fuzzer/Dissertation/execution-engine/./executio_engine.py", line 150, in run_test
    driver = create_webdriver(browser_name)
  File "/home/dhia/browser-fuzzer/Dissertation/execution-engine/./executio_engine.py", line 102, in create_webdriver
    driver = webdriver.Chrome(
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 132
Current browser version is 134.0.6988.0 with binary path /home/dhia/chrome-asan/chrome-asan/chrome
Stacktrace:
#0 0x5944ef17b53a <unknown>
#1 0x5944eec76f00 <unknown>
#2 0x5944eecb5342 <unknown>
#3 0x5944eecb4235 <unknown>
#4 0x5944eecae361 <unknown>
#5 0x5944eecaa4b6 <unknown>
#6 0x5944eecf77b6 <unknown>
#7 0x5944eecf6e06 <unknown>
#8 0x5944eeceb343 <unknown>
#9 0x5944eecb878a <unknown>
#10 0x5944eecb99de <unknown>
#11 0x5944ef1452cb <unknown>
#12 0x5944ef149242 <unknown>
#13 0x5944ef1327ac <unknown>
#14 0x5944ef149df7 <unknown>
#15 0x5944ef116b2f <unknown>
#16 0x5944ef16a1a8 <unknown>
#17 0x5944ef16a370 <unknown>
#18 0x5944ef17a3b6 <unknown>
#19 0x787a90894ac3 <unknown>


2025-02-14 13:26:01,096 - INFO - ====== WebDriver manager ======
2025-02-14 13:26:01,594 - INFO - Get LATEST geckodriver version for 134.0 firefox
2025-02-14 13:26:01,594 - INFO - GH_TOKEN will be used to perform requests
2025-02-14 13:26:02,322 - INFO - Get LATEST geckodriver version for 134.0 firefox
2025-02-14 13:26:02,322 - INFO - GH_TOKEN will be used to perform requests
2025-02-14 13:26:02,919 - INFO - Driver [/home/dhia/.wdm/drivers/geckodriver/linux64/v0.35.0/geckodriver] found in cache
2025-02-14 13:26:18,559 - INFO - [firefox] Loading: file:///home/dhia/browser-fuzzer/Dissertation/tests/testing_seeds/combined/id:013729,time:0,execs:0,orig:rex-in-monospace.html
2025-02-14 13:26:30,822 - INFO - ====== WebDriver manager ======
2025-02-14 13:26:30,944 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-14 13:26:31,041 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-14 13:26:31,120 - INFO - Driver [/home/dhia/.wdm/drivers/chromedriver/linux64/132.0.6834.159/chromedriver-linux64/chromedriver] found in cache
2025-02-14 13:26:34,038 - ERROR - [chrome] ERROR: Message: session not created: This version of ChromeDriver only supports Chrome version 132
Current browser version is 134.0.6988.0 with binary path /home/dhia/chrome-asan/chrome-asan/chrome
Stacktrace:
#0 0x5bf183ebc53a <unknown>
#1 0x5bf1839b7f00 <unknown>
#2 0x5bf1839f6342 <unknown>
#3 0x5bf1839f5235 <unknown>
#4 0x5bf1839ef361 <unknown>
#5 0x5bf1839eb4b6 <unknown>
#6 0x5bf183a387b6 <unknown>
#7 0x5bf183a37e06 <unknown>
#8 0x5bf183a2c343 <unknown>
#9 0x5bf1839f978a <unknown>
#10 0x5bf1839fa9de <unknown>
#11 0x5bf183e862cb <unknown>
#12 0x5bf183e8a242 <unknown>
#13 0x5bf183e737ac <unknown>
#14 0x5bf183e8adf7 <unknown>
#15 0x5bf183e57b2f <unknown>
#16 0x5bf183eab1a8 <unknown>
#17 0x5bf183eab370 <unknown>
#18 0x5bf183ebb3b6 <unknown>
#19 0x76f954494ac3 <unknown>

2025-02-14 13:26:34,039 - ERROR - Traceback (most recent call last):
  File "/home/dhia/browser-fuzzer/Dissertation/execution-engine/./executio_engine.py", line 150, in run_test
    driver = create_webdriver(browser_name)
  File "/home/dhia/browser-fuzzer/Dissertation/execution-engine/./executio_engine.py", line 102, in create_webdriver
    driver = webdriver.Chrome(
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 132
Current browser version is 134.0.6988.0 with binary path /home/dhia/chrome-asan/chrome-asan/chrome
Stacktrace:
#0 0x5bf183ebc53a <unknown>
#1 0x5bf1839b7f00 <unknown>
#2 0x5bf1839f6342 <unknown>
#3 0x5bf1839f5235 <unknown>
#4 0x5bf1839ef361 <unknown>
#5 0x5bf1839eb4b6 <unknown>
#6 0x5bf183a387b6 <unknown>
#7 0x5bf183a37e06 <unknown>
#8 0x5bf183a2c343 <unknown>
#9 0x5bf1839f978a <unknown>
#10 0x5bf1839fa9de <unknown>
#11 0x5bf183e862cb <unknown>
#12 0x5bf183e8a242 <unknown>
#13 0x5bf183e737ac <unknown>
#14 0x5bf183e8adf7 <unknown>
#15 0x5bf183e57b2f <unknown>
#16 0x5bf183eab1a8 <unknown>
#17 0x5bf183eab370 <unknown>
#18 0x5bf183ebb3b6 <unknown>
#19 0x76f954494ac3 <unknown>


2025-02-14 13:26:34,045 - INFO - ====== WebDriver manager ======
2025-02-14 13:26:34,351 - INFO - Get LATEST geckodriver version for 134.0 firefox
2025-02-14 13:26:34,351 - INFO - GH_TOKEN will be used to perform requests
2025-02-14 13:26:34,913 - INFO - Get LATEST geckodriver version for 134.0 firefox
2025-02-14 13:26:34,913 - INFO - GH_TOKEN will be used to perform requests
2025-02-14 13:26:35,456 - INFO - Driver [/home/dhia/.wdm/drivers/geckodriver/linux64/v0.35.0/geckodriver] found in cache
2025-02-14 13:26:47,650 - INFO - [firefox] Loading: file:///home/dhia/browser-fuzzer/Dissertation/tests/testing_seeds/combined/id:000128,time:0,execs:0,orig:fuzz-00011.mut6.html
2025-02-14 13:27:06,095 - INFO - ====== WebDriver manager ======
2025-02-14 13:27:06,235 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-14 13:27:06,338 - INFO - Get LATEST chromedriver version for google-chrome
2025-02-14 13:27:06,438 - INFO - Driver [/home/dhia/.wdm/drivers/chromedriver/linux64/132.0.6834.159/chromedriver-linux64/chromedriver] found in cache
2025-02-14 13:27:10,355 - ERROR - [chrome] ERROR: Message: session not created: This version of ChromeDriver only supports Chrome version 132
Current browser version is 134.0.6988.0 with binary path /home/dhia/chrome-asan/chrome-asan/chrome
Stacktrace:
#0 0x624d9c85e53a <unknown>
#1 0x624d9c359f00 <unknown>
#2 0x624d9c398342 <unknown>
#3 0x624d9c397235 <unknown>
#4 0x624d9c391361 <unknown>
#5 0x624d9c38d4b6 <unknown>
#6 0x624d9c3da7b6 <unknown>
#7 0x624d9c3d9e06 <unknown>
#8 0x624d9c3ce343 <unknown>
#9 0x624d9c39b78a <unknown>
#10 0x624d9c39c9de <unknown>
#11 0x624d9c8282cb <unknown>
#12 0x624d9c82c242 <unknown>
#13 0x624d9c8157ac <unknown>
#14 0x624d9c82cdf7 <unknown>
#15 0x624d9c7f9b2f <unknown>
#16 0x624d9c84d1a8 <unknown>
#17 0x624d9c84d370 <unknown>
#18 0x624d9c85d3b6 <unknown>
#19 0x7a5fa8e94ac3 <unknown>

2025-02-14 13:27:10,356 - ERROR - Traceback (most recent call last):
  File "/home/dhia/browser-fuzzer/Dissertation/execution-engine/./executio_engine.py", line 150, in run_test
    driver = create_webdriver(browser_name)
  File "/home/dhia/browser-fuzzer/Dissertation/execution-engine/./executio_engine.py", line 102, in create_webdriver
    driver = webdriver.Chrome(
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/dhia/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 132
Current browser version is 134.0.6988.0 with binary path /home/dhia/chrome-asan/chrome-asan/chrome
Stacktrace:
#0 0x624d9c85e53a <unknown>
#1 0x624d9c359f00 <unknown>
#2 0x624d9c398342 <unknown>
#3 0x624d9c397235 <unknown>
#4 0x624d9c391361 <unknown>
#5 0x624d9c38d4b6 <unknown>
#6 0x624d9c3da7b6 <unknown>
#7 0x624d9c3d9e06 <unknown>
#8 0x624d9c3ce343 <unknown>
#9 0x624d9c39b78a <unknown>
#10 0x624d9c39c9de <unknown>
#11 0x624d9c8282cb <unknown>
#12 0x624d9c82c242 <unknown>
#13 0x624d9c8157ac <unknown>
#14 0x624d9c82cdf7 <unknown>
#15 0x624d9c7f9b2f <unknown>
#16 0x624d9c84d1a8 <unknown>
#17 0x624d9c84d370 <unknown>
#18 0x624d9c85d3b6 <unknown>
#19 0x7a5fa8e94ac3 <unknown>


2025-02-14 13:27:10,367 - INFO - ====== WebDriver manager ======
2025-02-14 13:27:10,916 - INFO - Get LATEST geckodriver version for 134.0 firefox
2025-02-14 13:27:10,916 - INFO - GH_TOKEN will be used to perform requests
2025-02-14 13:27:11,743 - INFO - Get LATEST geckodriver version for 134.0 firefox
2025-02-14 13:27:11,744 - INFO - GH_TOKEN will be used to perform requests
2025-02-14 13:27:12,429 - INFO - Driver [/home/dhia/.wdm/drivers/geckodriver/linux64/v0.35.0/geckodriver] found in cache
2025-02-14 13:27:27,739 - INFO - [firefox] Loading: file:///home/dhia/browser-fuzzer/Dissertation/tests/testing_seeds/combined/id:043977,time:0,execs:0,orig:color-valid.html
