<!doctype html>
<html>
 <head>
  <div><script src="/resources/testharnessreport.js"></script></div><div><script src="/resources/testharnessreport.js"></script></div>
  <div id=log><script src="/resources/testharness.js"></script></div>
  <title>&lt;body onerror> - runtime error in &lt;script></title>
 </head>
  <script>
    setup({allow_uncaught_exception:true});
    var t = async_test();
    var t_col = async_test(document.title+' (column)');
    var ran = false;
  </script>
 <body onerror="
    t.step(function(){
        ran = true;
        assert_equals(typeof event, 'string', 'first arg');
        assert_equals(source, location.href, 'second arg');
        assert_equals(typeof lineno, 'number', 'third arg');
    });
    t_col.step(function(){
        assert_equals(typeof colno, 'number', 'fourth arg');
    });
    t_col.step(function(){
        t_col.done();
    });
  </script>
 </body>
</html>
