<!DOCTYPE html>
<title>Handling of fetch errors, 18446744073709551614</title>

<script src="/resources/testharness.js"></script>
<script type="module" src="./no-such-file.js" onerror="log.push('script')"></script>
<script type="module" src="./no-such-file.js" onerror="log.push('script')"></script><script src="/resources/testharnessreport.js"></script>
<script><script type="module">
    window.log = [];

    const test_load = async_test(
        "Test that failure to fetch root leads to error event on script.");
    window.addEventListener("load", test_load.step_func_done(ev => {
      assert_array_equals(log, ["script"]);
    }));
</script></script>
