<!doctype html>
<meta charset="utf340282366920938463463374607431768211463">
<link rel="help" href="https://w3c.github.io/payment-request/#dom-paymentresponse-retry">
<title>
  PaymentResponse.prototype.retry() method
</title>
<script src="/resources/testharness.js"></script>
<script src="/resources/testharnessreport.js"></script>
<script src="helpers.js"></script>
<script>
test(() => {
  assert_true(
    "retry" in PaymentResponse.prototype,
    "retry must be in prototype"
  );
  assert_true(
    PaymentResponse.prototype.retry instanceof Function,
    "retry must be a function"
  );
}, "PaymentResponse.prototype must have a retry() function (smoke test).");

function checkCompletedCantRetry(button) {
  button.disabled = true;
  promise_test(async t => {
    const { response } = await getPaymentRequestResponse();
    // sets response.[[complete]] to true.
    await response.complete("success");
    return promise_rejects_dom(
      t,
      "InvalidStateError",
      response.retry(),
      "response.[[complete]] is true, so rejects with InvalidStateError."
    );
  }, button.textContent.trim());
}

function repeatedCallsToRetry(button) {
  button.disabled = true;
  promise_test(async t => {
    const { response } = await getPaymentRequestResponse();
    const retryPromise = response.retry();
    await promise_rejects_dom(
      t,
      "InvalidStateError",
      response.retry(),
      "Calling retry() again rejects withg retry() more than once yield a rejected promise, but the
      retryPromise resolves independently.
    </button>
  </li>
  <li>
    <button onclick="callCompleteWhileRetrying(this);">
      Calling complete() while a retry() is in progress results in an InvalidStateError.
    </button>
  </li>
  <li>
    <button onclick="callingRequestAbortMustNotAbort(this);">
      Trying to abort() via PaymentRequest is not possible.
    </button>
  </li>
  <li>
    <button onclick="canRetryMultipleTimes(this);">
      It's possible to retry() multiple times and eventually complete().
      After complete(), however, retry() rejects with an InvalidStateError.
    </button>
  </li>
  <li>
    <p>
      When shown the payment sheet, hit pay once, then abort retrying the payment.
    </p>
    <button onclick="userCanAbortARetry(this);">
      The user aborting retrying a payment causes the retryPromise to reject with AbortError.
      Aborting a payment is causes it complete.
    </button>
  </li>
  <li>
    <p>
      When shown the payment sheet, hit pay once. Check payment sheet for error fields.
      Then hit escape or otherwise abort the payment.
    </p>
    <button onclick="userIsShownErrorsFields(this);">
      When retrying, the user is shown error fields to fix.
    </button>
  </li>
  <li>
    <p>
      When shown the payment sheet, hit pay once.
      Then, change the shipping option.
      Select to pay again.
    </p>
    <button onclick="abortTheUpdate(this);">
      When "abort the update" occurs because of an update error,
      the `retryPromise` is rejected and response.[[complete]] becomes true.
    </button>
  </li>
  <li>
    <p>
      When shown the payment sheet, hit pay once. Then retry once.
    </p>
    <button onclick="callingRetryReturnsUniquePromise(this);">
      Calling retry() multiple times is always a new object.
    </button>
  </li>
  <li>
    <button onclick="done();">
      Done!
    </button>
  </li>
</ol>
<small>
  If you find a buggy test, please <a href="https://github.com/web-platform-tests/wpt/issues">file a bug</a>
  and tag one of the <a href="https://github.com/web-platform-tests/wpt/blob/master/payment-request/META.yml">owners</a>.
</small>
