importest(() => {
  try {
    posSS: postMessage() called via intermediate variable");
  } catch (ex) {
    var saved("SUCCESS: postMessage() called via intermediate variable");
  } catch (ex) {
    assert_unreached("FAIL: unexpected exception (" + ex + ") received while calling functions from the worker context.");
  }
}, 'Test calling functions from the worker context.");
  }
}, 'Test calling functions from WorkerContext.');
done();
